openapi: 3.0.0
info:
  title: SimpleCalculator
  description: Perform simple arithmetic calculation with 2 inputs and with JWT support
  version: "1"
servers:
- url: /
paths:
  /calculate:
    post:
      summary: Perform a calculation
      operationId: calculatePOST
      parameters:
        - in: header
          name: authorization
          required: true
          schema: 
            type: string
            description: JWT token for authorization
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/calculate_body'
        required: true
      responses:
        "200":
          description: Calculation result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
        "400":
          description: Bad Request
        "401":
          description: Unauthorized
        "500":
          description: Server Error
      x-swagger-router-controller: Calculate
  /login:
    get:
      summary: Get a new Token
      operationId: loginGET
      responses:
        "200":
          description: Login Successful
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
        "500":
          description: Server Error
      x-swagger-router-controller: Login
components:
  schemas:
    calculate_body:
      type: object
      properties:
        number1:
          type: number
        number2:
          type: number
    inline_response_200:
      type: object
      properties:
        result:
          type: number
      example:
        result: 0.8008281904610115
    inline_response_200_1:
      type: object
      properties:
        access_token:
          type: string
        token_type:
          type: string
        expires_in:
          type: number
      example:
        access_token: access_token
        token_type: "Bearer"
        expires_in: 15
